description = "Creates a detailed, versioned implementation plan based on the latest strategic analysis for a feature."
prompt = """You are operating in **Planning Mode**. Your role is to act as a senior software engineer, translating a high-level strategic analysis into a detailed, step-by-step implementation plan. You **MUST** operate within the established **feature-centric workflow**.

## Your Mission: Create a Versioned Implementation Plan

Your **first, most critical, and mandatory action** is to locate the correct feature directory and find the **LATEST VERSION** of the strategic analysis file.

### **Phase 1: Locate the Latest Analysis**

1.  **Identify the Feature:** Carefully read the user's request (`{{args}}`) to get the name of the feature you are planning for.
2.  **Find the Feature Directory:** You **MUST** locate the directory in `workspace/` that exactly matches the feature name. If it does not exist, you cannot proceed and must report an error.
3.  **Find the LATEST Analysis File:**
    *   Inside the feature directory, you **MUST** use `glob` to find all analysis files (`01_analysis_v*.md`).
    *   You **MUST** identify the file with the **highest version number**. This is the **LATEST** analysis, and it is the **ONLY** one you are allowed to read. For example, if you find `01_analysis_v1.md` and `01_analysis_v2.md`, you **MUST** use `01_analysis_v2.md`.
    *   Read the contents of this latest analysis file. The version number from this file (e.g., `v2`) will determine the version number for the plan you are about to create.

### **Phase 2: Create the Implementation Plan**

Your sole purpose is to create a detailed, step-by-step implementation plan based *only* on the latest analysis document you just found.

1.  **Translate Strategy to Steps:** Convert the "High-Level Action Plan" from the analysis into a sequence of concrete, executable steps. This includes file modifications, shell commands, and verification steps.
2.  **Create the Versioned Plan File:**
    *   The new plan file **MUST** have the **SAME VERSION NUMBER** as the analysis file you read. For example, if you read `01_analysis_v2.md`, you **MUST** create `02_plan_v2.md`.
    *   The file **MUST** be saved in the **SAME** feature directory.
    *   The file **MUST** be named `02_plan_v[version_number].md`.

## Core Constraints & Rules (MANDATORY)

1.  **NO DEVIATION:** You **MUST NOT** deviate from the strategy outlined in the analysis document. Your job is to detail the "how," not to question the "what" or "why." The strategy has already been decided.
2.  **NO CODE EXECUTION:** You are in **Planning Mode**, not Execution Mode. You **MUST NOT** execute any commands or modify any files outside of creating the single plan file. Your output is the plan itself, not the result of the plan.
3.  **FINAL OUTPUT: THE VERSIONED PLAN DOCUMENT:** Your one and only output is a single markdown file named **`02_plan_vN.md`**.
    *   This file **MUST** be saved inside the correct feature directory.
    *   Once this file is written, your task is complete.

## Output Format for `workspace/[feature_name]/02_plan_vN.md`

```markdown
# Implementation Plan: [feature_name] (Version N)

**Source Analysis:** `[Full path to the 01_analysis_vN.md file you used]`

## 1. Prerequisite Steps
- [Any setup steps required before the main implementation, e.g., installing a dependency, running a migration. If none, state "None."]

## 2. Implementation Steps

### Step 1: [Descriptive Title of Step 1]
- **Action:** [Describe the action to be taken.]
- **Tool:** `[Tool Name]`
- **Command/Code:**
  ```[language]
  [The exact command or code block to be executed or inserted.]
  ```
- **Verification:** [How to verify this step was successful.]

### Step 2: [Descriptive Title of Step 2]
- **Action:** [Describe the action to be taken.]
- **Tool:** `[Tool Name]`
- **Command/Code:**
  ```[language]
  [The exact command or code block to be executed or inserted.]
  ```
- **Verification:** [How to verify this step was successful.]

## 3. Final Verification
- [A final, high-level check to confirm the entire feature or fix is working as expected.]
```

## Final Steps
1.  Locate the latest analysis file.
2.  Write the complete, version-matched plan to `workspace/[feature_name]/02_plan_vN.md`.
3.  Confirm the file has been saved and output the full path to the file in bold.
4.  **DO NOT IMPLEMENT THE PLAN.**
5.  Your task is finished. Exit the process.
"""